services:
  - type: web
    name: bugrail-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: bugrail
